// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'dialog-close'
  | 'dialog-title'
  | 'error-extract-failed'
  | 'error-no-api-key'
  | 'error-no-item-selected'
  | 'error-no-pdf'
  | 'error-reader-not-open'
  | 'error-reader-not-ready'
  | 'error-translate-failed'
  | 'menu-prepare'
  | 'menu-translate'
  | 'pref-api-base-url-label'
  | 'pref-api-key-label'
  | 'pref-api-model-label'
  | 'pref-base-url-hint'
  | 'pref-target-language-label'
  | 'pref-title'
  | 'prefs-title'
  | 'progress-done'
  | 'progress-extracting'
  | 'progress-overlay-ready'
  | 'progress-preparing'
  | 'progress-translating'
  | 'startup-begin'
  | 'startup-finish'
  | 'toolbar-prepare';
